---
version: '3'

vars:
  CURDIR:
    sh: pwd
  SOURCE_FOLDER: src

tasks:
  default:
    cmds:
      - task: test
      - task: build

  mod:
    desc: update go modules, add submodules to go root
    cmds:
      - cmd: |
          export SOURCE_FOLDER={{.SOURCE_FOLDER}}
          curl -sL https://raw.githubusercontent.com/triole/ghwfe/master/sh/go_add_sub_packages.sh | bash

  build:
    desc: build binary using remote ghwfe script, requires curl
    cmds:
      - cmd: |
          export SOURCE_FOLDER={{.SOURCE_FOLDER}}
          curl -sL https://raw.githubusercontent.com/triole/ghwfe/master/sh/go_build.sh | bash

  test:
    desc: run go tests
    cmds:
      - cmd: go test ./... -v -coverpkg=./... -race -bench=.

  deploy:
    desc: build and copy to my personal arch mybins folder
    cmds:
      - task: build
      - cmd: cp -rpf build/* ${HOME}/tools/arch/mybins/

  docker:
    desc: run docker to test memory issue inside
    dir: testdata
    cmds:
      - cmd: cp "{{.CURDIR}}/build/linux_x86_64/fileaxe" "{{.CURDIR}}/testdata/bin/"
      - cmd: cp "$(which fakedata)" "{{.CURDIR}}/testdata/bin/"
      - cmd: docker build --tag logaxe-test .
      - cmd: >-
          docker ps -a | grep logaxe-test | grep -Po "^[0-9a-f]+"
          | xargs -i docker rm {}
      - cmd: >-
          docker run --kernel-memory="64m" --memory-swap="128m"
          --memory="128m" --name logaxe-test logaxe-test
